language: python
python:
    - "2.6"
    - "2.7"
    - "3.5"
    - "3.6"
env:
    - TORNADO=4.5
install:
    - pip install -q tornado==$Tornado --use-mirrors
    - pip install pep8 --use-mirrors
before_script:
    - "pep8 --exclude=migrations --ignore=E501,E225 src"
script:
    - python3 app.py
